Models/CalcViewModel.cs
namespace WebTeploobmenApp.Models
{
    public class CalcViewModel : Formulas.Data
    {
        public double[,] ResultTable { get; set; }
        public List<double> LayerPositions { get; set; }
        public List<double> MaterialTemperatures { get; set; }
        public List<double> GasTemperatures { get; set; }
        public List<double> TemperatureDifferences { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace WebTeploobmenApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebTeploobmenApp.Data;

namespace WebTeploobmenApp.Controllers
{
    public class AuthController : Controller
    {
        private readonly TeploobmenContext _context;
        public AuthController(TeploobmenContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(string login, string password)
        {
            var user = _context.Users.FirstOrDefault(x => x.Login == login && x.Password == password);
            if (user != null)
            {
                var claims = new List<Claim> {
                    new Claim("UserId", user.Id.ToString()),
                    new Claim(ClaimTypes.Name, login),
                };
                ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "Cookies");
                await HttpContext.SignInAsync("Cookies", new ClaimsPrincipal(claimsIdentity));
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using WebTeploobmenApp.Data;
using WebTeploobmenApp.Models;

namespace WebTeploobmenApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly TeploobmenContext _context;

        public HomeController(ILogger<HomeController> logger, TeploobmenContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var variants = _context.Variants
                .Where(x => x.UserId == null || x.UserId == GetUserId())
                .ToList();
            return View(variants);
        }

        public IActionResult Parameters(int id)
        {
            Variant variant = GetVariant(id) ?? new Variant();
            Formulas.Data data = variant;
            return View(data);
        }

        public IActionResult Calc(CalcViewModel viewModel)
        {
            int yCount = viewModel.H0 * 2 + 1;
            double[,] result = new double[yCount, 8];

            for (int y = 0; y < yCount; y++)
            {
                double y2 = y / 2.0;
                result[y, 0] = Formulas.CalcY(viewModel, y2);
                result[y, 1] = Formulas.Calc1exp(viewModel, y2);
                result[y, 2] = Formulas.Calc1mexp(viewModel, y2);
                result[y, 3] = Formulas.CalcV(viewModel, y2);
                result[y, 4] = Formulas.CalcO(viewModel, y2);
                result[y, 5] = Formulas.CalcT1(viewModel, y2);
                result[y, 6] = Formulas.CalcT2(viewModel, y2);
                result[y, 7] = Formulas.CalcTDifference(viewModel, y2);
                for (int i = 0; i < 8; i++)
                {
                    result[y, i] = Math.Round(result[y, i], 2);
                }
            }

            viewModel.MaterialTemperatures = new List<double>();
            viewModel.GasTemperatures = new List<double>();
            viewModel.LayerPositions = new List<double>();
            viewModel.TemperatureDifferences = new List<double>();
            for (int i = 0; i < yCount; i++)
            {
                viewModel.LayerPositions.Add(i / 2.0);
                viewModel.MaterialTemperatures.Add(result[i, 5]);
                viewModel.GasTemperatures.Add(result[i, 6]);
                viewModel.TemperatureDifferences.Add(result[i, 7]);
            }

            viewModel.ResultTable = result;

            _context.Variants.Add(new Variant(viewModel) { UserId = GetUserId() });
            _context.SaveChanges();

            return View(viewModel);
        }

        public IActionResult Delete(int id)
        {
            Variant? variant = GetVariant(id);
            if (variant != null)
            {
                _context.Variants.Remove(variant);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        private int? GetUserId()
        {
            var userIdStr = User.FindFirst("UserId")?.Value;
            int? userId = userIdStr == null ? null : int.Parse(userIdStr);
            return userId;
        }
        private Variant GetVariant(int id)
        {
            return _context.Variants.FirstOrDefault(x => x.Id == id && (x.UserId == GetUserId() || x.UserId == null));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Calc.cshtml
@model CalcViewModel
@{
    ViewData["Title"] = "Home Page";

    string[] rowNames = [
        "Y",
        "1-exp",
        "1-m*exp",
        "v",
        "o",
        "t",
        "T",
        "delta T",
    ];
}

<div class="text-center">
    Результаты расчёта:<br />
    <table class="table table-hover">
        <tr>
            <th>Координаты y, м</th>
            @for (int y = 0; y < Model.ResultTable.GetLength(0); y++)
            {
                <th>@(y/2.0)</th>
            }
        </tr>

        @for (int i = 0; i < Model.ResultTable.GetLength(1); i++)
        {
            <tr>
                <td>@rowNames[i]</td>
                @for (int y = 0; y < Model.ResultTable.GetLength(0); y++)
                {
                    <td>@Model.ResultTable[y, i]</td>
                }
            </tr>
        }
    </table>

    <div id="chart1"></div>
    <div id="chart2"></div>
    <script>
        var layerPositions = @Json.Serialize(Model.LayerPositions);
        layerPositions.unshift("x");
        var materialTemps = @Json.Serialize(Model.MaterialTemperatures);
        materialTemps.unshift("Температура окатышей, С");
        var gasTemps = @Json.Serialize(Model.GasTemperatures);
        gasTemps.unshift("Температура воздуха, С");
        var tempsDiffs = @Json.Serialize(Model.TemperatureDifferences);
        tempsDiffs.unshift("Разность температур, С");
        var chart = c3.generate({
            bindto: '#chart1',
            data: {
                x: 'x',
                columns: [
                    layerPositions,
                    materialTemps,
                    gasTemps,
                ]
            }
        });
        var chart2 = c3.generate({
            bindto: '#chart2',
            data: {
                x: 'x',
                columns: [
                    layerPositions,
                    tempsDiffs,
                ]
            }
        });
    </script>
</div>

Views/Home/Index.cshtml
@model List<Variant>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <button onclick="location.href='/home/parameters/0'" type="button" class="btn btn-primary">Новый расчёт</button>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Номер варианта</th>
                @foreach(var param in Formulas.Data.GetParameters())
                {
                    <th>@param.Name</th>
                }
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            @foreach(Variant variant in Model)
            {
                <tr>
                    <td>@variant.Id</td>
                    @foreach(var param in Formulas.Data.GetParameters(variant))
                    {
                        <td>@param.Value</td>
                    }
                    <td>
                        <a href="/home/parameters/@variant.Id">Расчёт</a>
                        <a href="/home/delete/@variant.Id">Удалить</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Home/Parameters.cshtml
@model Formulas.Data
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <form action="/home/calc" method="post">
        @foreach (var parameter in Formulas.Data.GetParameters(Model))
        {
            <div class="mb-3">
                <label class="form-label">@parameter.Name</label>
                <input type="text" class="form-control" name="@parameter.Param" value="@parameter.Value">
            </div>
        }
        <button class="btn btn-primary">Рассчитать</button>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebTeploobmenApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebTeploobmenApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/c3.min.css" />
    <script src="~/js/d3-5.8.2.min.js" asp-append-version="true"></script>
    <script src="~/js/c3.min.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebTeploobmenApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Выйти</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Index">Войти</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebTeploobmenApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>